name: openBracket
favicon: null
layout_spectrum: 0.3680524055380374
typography_spectrum: 0.2404121735598892
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0.41602546046487987
  rhythmicContrast: 0.25
purpose: []
